### ISSUE TITLE
apiservice v1alpha1.tenancy.kiosk.sh is unready even though kiosk is running

### ISSUE THREAD

**Issue by iliyahoo** [kiosk-sh/kiosk#88] opened 2020-09-20 20:19 UTC
I'm getting an error on the kiosk pod:

controller.go:498] unable to retrieve the complete list of server APIs: tenancy.kiosk.sh/v1alpha1: the server is currently unable to handle the request

Helm chart: kiosk-0.1.20
Kubernetes: v1.16.13-gke.1 (**GKE**)

Please have a look on the attached kiosk pod's log.
[kiosk.log](https://github.com/kiosk-sh/kiosk/files/5252527/kiosk.log)

**Comment by FabianKramm** [comment] 2020-09-21 07:22
@iliyahoo thanks for reporting this issue! Does kiosk crash because of this error or is it only displayed in the logs?

**Comment by iliyahoo** [comment] 2020-09-21 09:15
Pod is running without restarts.
Only this error is displayed in logs.

`$ kc get po
NAME                     READY   STATUS    RESTARTS   AGE
kiosk-746bbcb4b4-mw79n   1/1     Running   0          15h`

`$ kc get crd | grep kiosk
accountquotas.config.kiosk.sh                         2020-09-16T19:40:28Z
accounts.config.kiosk.sh                              2020-09-16T19:40:28Z
templateinstances.config.kiosk.sh                     2020-09-16T19:40:28Z
templates.config.kiosk.sh                             2020-09-16T19:40:28Z
`

**Comment by FabianKramm** [comment] 2020-09-21 12:51
@iliyahoo ah okay I see! Yes this can occur and shouldn't have any effect on kiosk itself, the problem is that the apiservice `v1alpha1.tenancy.kiosk.sh` is not ready yet, but already registered at the kubernetes api server, it will be ready after kiosk started though.

**Comment by iliyahoo** [comment] 2020-09-21 13:59
**$ cat <<EOF | kc apply -f -**
> ---
> apiVersion: tenancy.kiosk.sh/v1alpha1
> kind: Account
> metadata:
>   name: johns-account
> spec:
>   space:
>     limit: 2
>   subjects:
>   - kind: User
>     name: john
>     apiGroup: rbac.authorization.k8s.io
> EOF
**error: unable to recognize "STDIN": no matches for kind "Account" in version "tenancy.kiosk.sh/v1alpha1"**

**Comment by iliyahoo** [comment] 2020-09-21 14:02
**$ kc api-resources | grep kiosk**
accountquotas                                      config.kiosk.sh                **false**        AccountQuota
accounts                                           config.kiosk.sh                **false**        Account
templateinstances                                  config.kiosk.sh                true         TemplateInstance
templates                                          config.kiosk.sh                **false**        Template
error: unable to retrieve the complete list of server APIs: tenancy.kiosk.sh/v1alpha1: the server is currently unable to handle the request

**Comment by FabianKramm** [comment] 2020-09-21 14:07
@iliyahoo okay does this still occur after:

```
kubectl delete apiservice v1alpha1.tenancy.kiosk.sh
kubectl delete pods --selector app=kiosk --namespace kiosk
```

**Comment by iliyahoo** [comment] 2020-09-21 14:27
Yes, it still persists after deleting apiservice and pod.

$ kubectl describe apiservice v1alpha1.tenancy.kiosk.sh
...
    Message:               failing or missing response from https://10.204.3.20:8443/apis/tenancy.kiosk.sh/v1alpha1: Get https://10.204.3.20:8443/apis/tenancy.kiosk.sh/v1alpha1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
...

**Comment by FabianKramm** [comment] 2020-09-21 14:42
@iliyahoo okay that is strange, after deleting apiservice and pod, it should definetely work, could you do a `kubectl version` that I can try to reproduce this problem?

**Comment by FabianKramm** [comment] 2020-09-21 14:55
@iliyahoo okay that is really strange, it should definitely work after deleting the apiservice and pod. I just tested it in gke with 1.16.13 and it works for me, even after deleting the deployment and recreating it. Maybe the service for the apiservice is somehow broken, can you do a `kubectl get apiservices | grep kiosk.sh`?

**Comment by iliyahoo** [comment] 2020-09-21 15:00
This is a **GKE** cluster.
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"**v1.16.13-gke.1**", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by iliyahoo** [comment] 2020-09-21 15:03
$ kubectl get apiservices | grep kiosk.sh
v1alpha1.config.kiosk.sh               Local                        True                           4h17m
v1alpha1.tenancy.kiosk.sh              kiosk/kiosk-apiservice       False (FailedDiscoveryCheck)   38m

$ kubectl get po --all-namespaces | grep kiosk
kiosk                  kiosk-746bbcb4b4-5dw4d                                           1/1     Running            0          40m
]$

**Comment by FabianKramm** [comment] 2020-09-21 15:32
@iliyahoo thanks for the information! Do you have a NetworkPolicy configured or is there any other special configuration in the GKE cluster?

**Comment by iliyahoo** [comment] 2020-09-21 16:07
I'll install a GKE cluster from scratch and retest it again.

**Comment by iliyahoo** [comment] 2020-09-21 17:14
Thank you very much, Fabian !
I've just deployed it on a fresh GKE cluster and there are not any errors.
The issue is definitely on my side.
Thank you again and I'm closing the issue.

**Comment by iliyahoo** [comment] 2020-09-21 20:25
You can reproduce the issue if you create a **private** GKE cluster.
It works on a public one.

**Comment by FabianKramm** [comment] 2020-09-22 07:37
@iliyahoo thanks for the information! Ah okay, yes that makes sense, the master API server cannot access kiosk, because it is not allowed to, since the cluster and the master are in two different VPCs. You'll have to allow this in GKE, for a similar issue check https://github.com/elastic/cloud-on-k8s/issues/1437

**Comment by FabianKramm** [comment] 2020-09-22 07:42
I'm closing this since it is mostly a GKE configuration issue and there is not much we can do in kiosk itself

**Closed by FabianKramm** 2020-09-22 07:42 UTC
Labels: area/manager, bug
